<?php
FLBuilder::render_module_css( 'pp-smart-button', $id, array(
	'style'						=> $settings->style,
	'display_icon'				=> $settings->display_icon,
	'icon'						=> $settings->icon,
	'icon_position'				=> $settings->icon_position,
	'icon_size'					=> $settings->icon_size,
	'icon_spacing'				=> $settings->icon_spacing,
	'button_effect'				=> $settings->button_effect,
	'button_effect_duration' 	=> $settings->button_effect_duration,
	'bg_color' 					=> $settings->bg_color,
	'bg_hover_color' 			=> $settings->bg_hover_color,
	'bg_color_primary' 			=> $settings->bg_color_primary,
	'bg_color_secondary' 		=> $settings->bg_color_secondary,
	'gradient_hover' 			=> $settings->gradient_hover,
	'text_color' 				=> $settings->text_color,
	'text_hover_color' 			=> $settings->text_hover_color,
	'width' 					=> $settings->width,
	'custom_width' 				=> $settings->custom_width,
	'align' 					=> $settings->align,
	'padding_top' 				=> $settings->padding_top,
	'padding_right' 			=> $settings->padding_right,
	'padding_bottom' 			=> $settings->padding_bottom,
	'padding_bottom' 			=> $settings->padding_bottom,
	'padding_left' 				=> $settings->padding_left,
	'padding_unit' 				=> 'px',
	'border' 					=> $settings->border,
	'border_hover_color' 		=> $settings->border_hover_color,
	'typography' 				=> $settings->typography,
) );